[profile.default]
src = "src"
out = "out"
libs = ["lib"]

evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# These settings should be used for snapshots
optimizer = true
optimizer_runs = 1000000

solc = "0.8.25"

bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 2048